package DFSApp;


/**
* DFSApp/ServerToServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DFS.idl
* Thursday, December 6, 2018 at 3:37:39 PM Eastern Standard Time
*/

public interface ServerToServerOperations 
{
  String readFile (String fileTitle) throws DFSApp.ServerToServerPackage.FileNotFoundFailure, DFSApp.ServerToServerPackage.FileLockedForWriteFailure;
  String readFileAndLockForWrite (String fileTitle) throws DFSApp.ServerToServerPackage.FileNotFoundFailure, DFSApp.ServerToServerPackage.FileLockedForWriteFailure;
  void lockFileForWrite (String fileTitle);
  void shutdown ();
  String echoYourHostName ();
} // interface ServerToServerOperations
