package DFSApp.ClientToServerPackage;

/**
* DFSApp/ClientToServerPackage/FileLockedForWriteFailureHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DFS.idl
* Thursday, December 6, 2018 at 3:37:39 PM Eastern Standard Time
*/

public final class FileLockedForWriteFailureHolder implements org.omg.CORBA.portable.Streamable
{
  public DFSApp.ClientToServerPackage.FileLockedForWriteFailure value = null;

  public FileLockedForWriteFailureHolder ()
  {
  }

  public FileLockedForWriteFailureHolder (DFSApp.ClientToServerPackage.FileLockedForWriteFailure initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DFSApp.ClientToServerPackage.FileLockedForWriteFailureHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DFSApp.ClientToServerPackage.FileLockedForWriteFailureHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DFSApp.ClientToServerPackage.FileLockedForWriteFailureHelper.type ();
  }

}
